### ISSUE TITLE
Passing an empty string as password causes a segfault

### ISSUE THREAD

**Issue by RosenGeorgiev** [karastojko/mailio#40]
This can be easily replicated with the <code>smtps_simple_msg</code> example.

This is the backtrace I get:
```
#0  0x00007ffff777aaf8 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string (this=0x7fffffffdb60, __str=<error reading variable: Cannot access memory at address 0x8>)
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/ext/new_allocator.h:82
#1  0x00007ffff7ecbc6c in std::operator+<char, std::char_traits<char>, std::allocator<char> > (__lhs=<error reading variable: Cannot access memory at address 0x8>, __rhs=0x7ffff7f629f7 "\r\n")
    at /usr/include/c++/10.1.0/bits/basic_string.h:6062
#2  0x00007ffff7ecfdc2 in mailio::dialog::send_sync<boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>&> > (this=0x55555558ea60, socket=..., 
    line=<error reading variable: Cannot access memory at address 0x8>) at /tmp/mailio/src/dialog.cpp:110
#3  0x00007ffff7ebc091 in mailio::dialog_ssl::send (this=0x55555558ea60, line=<error reading variable: Cannot access memory at address 0x8>) at /tmp/mailio/src/dialog.cpp:277
#4  0x00007ffff7f5fd08 in mailio::smtp::auth_login (this=0x7fffffffde10, username="example@gmail.com", password="") at /tmp/mailio/src/smtp.cpp:197
#5  0x00007ffff7f60772 in mailio::smtps::authenticate (this=0x7fffffffde10, username="example@gmail.com", password="", method=mailio::smtps::auth_method_t::START_TLS) at /tmp/mailio/src/smtp.cpp:312
#6  0x000055555556890f in main () at /tmp/mailio/examples/smtps_simple_msg.cpp:45
```
The same code works fine when you provide a password. If the lack of password is an issue, I would expect an exception to be thrown or an error code to be returned.

Happens on:
Arch
gcc-10.1.0
mailio compiled from the master branch

**Comment by karastojko** [comment]
Hi,
Thanks for reporting the issue. Please check the latest commit on the master branch.

Regards
